version: '3.8'
services:
  comfort-model-api:
    build: .
    container_name: comfort-model-api
    network_mode: host
    restart: always
    environment:
      - RULE_ENGINE_URL=http://localhost:10263/api/v1/comfort    
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
